config/routes.rb
Rails.application.routes.draw do
resources :tweets
get '/tweets/:id', to: 'tweets#show' 
get '/tweets/:id', to: 'tweets#get_image'
root'tweets#index'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :message, length: { maximum: 140 }  
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end
  
  def new
   @tweet = Tweet.new
  end
  
def create
    message = params[:tweet][:message]
    tweets = Tweet.new(message: message)
    tdate = params[:tweet][:tdate]
    tdate = Time.current
    tweets = Tweet.new(message: message, tdate: tdate)
    file = params[:tweet][:file].read
    tweets = Tweet.new(message: message, tdate: tdate, file: file)
    @tweet = Tweet.new(message: message, tdate: tdate, file: file)
    if @tweet.save
    flash[:notice] = "画像を保存しました。"
    redirect_to root_path 
    else
    flash[:notice] = "保存できませんでした"
    redirect_to "new"
    end
end 
  
  def destroy 
  tweets = Tweet.find(params[:id]) 
  tweets.destroy 
  redirect_to root_path
  end 

  def get_image 
   @tweet = Tweet.find(params[:id]) 
   send_data @tweet.file, :disposition => "inline", type: 'tweet/png' 
  end 

  def show
  @tweet = Tweet.find(params[:id]) 
  end  
 
  def edit 
  @tweet = Tweet.find(params[:id]) 
  end  

  def update 
  @tweet = Tweet.find(params[:id]) 
  message = params[:tweet][:message] 
  @tweet.update(message: message) 
  file = params[:tweet][:file].read
  @tweet.update(message: message, file: file)
  redirect_to root_path
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id  ="container">
  <div id ="header",float= left;>
    <%= render "header"%>
    </div>
    
    <div class="logo">
    &nbsp;&nbsp;<%= image_tag 'kinki.jpg' %>
   </div>   

     <div id = "sidebar">
      <%= render "sidebar" %>
    </div>
    <div id= "content" ,text-align= center;>
      <%= yield %>
    </div>
    
    <div id = "footer">
      <%= render "footer" %>
    </div>
  </div>
</body>
</html>

app/views/tweets/_footer.html.erb
  <p>Copyright &copy; Kindai University 2018 All Rights Reservered.</p>

app/views/tweets/_form.html.erb
<p><%= f.label :message, '内容' %> 
<%= f.text_field :message ,:size => "90*90" %></p> 
<p><%= f.label :file, 'ファイル' %> • <%= f.file_field :file , multipart: true%></p>
<%= f.submit 'ツィート' %>

app/views/tweets/_header.html.erb
<p>ホーム　モーメント　通知　メッセージ　マーク　キーワード検索　アイコン　<%= link_to 'ツイート', new_tweet_path ,class:"btn" %></p>

app/views/tweets/_sidebar.html.erb
<p>近畿大学<br>
@kinkidaigakuPR</p>
<p>近畿大学総務部広報室のTwitter公式アカウントです。
近畿大学ホームページの更新情報を中心に、
大学に関する情報を発信していきます。
個別DMでのお問い合わせには返信を行っておりませんので、ご了承ください。</p>

大阪府東大阪市<br>
 <a href="instagram.com/kinkidaigakupr/">instagram.com/kinkidaigakupr/</a><br>
2010年12月に登録

<p class="btn"><%= link_to 'ツイート', new_tweet_path %>&nbsp;<%= link_to 'ダイレクト...', new_tweet_path %></p>

app/views/tweets/edit.html.erb
 <% if @tweet.errors.present? %> 
 <h3>エラーがあります。</h3>
 <ul <% @tweet.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
 <% end %> 
 </ul>
 <% end %> 
 
<%= form_for @tweet, url: {action: :update} do |f| %> 
<%= render partial: "form", :locals => {:f => f} %>
<% end %>

app/views/tweets/index.html.erb
<% @tweets.each do |tweets| %>
<p><%= image_tag('kinki.jpg') %>近畿大学&nbsp;@kinkidaigakuPR ・<%= (Time.current - tweets.tdate).to_i/60 %> 分前</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=tweets.message%><br>
<%= link_to image_tag(tweet_path(tweets), :width => 100),tweet_path(tweets) %> 
</p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to '削除', tweet_path(tweets), method: :delete %>
<%= link_to '表示', tweet_path(tweets) %>
<%= link_to '編集', edit_tweet_path(tweets) %>
<% end %>

app/views/tweets/new.html.erb
 <% if @tweet.errors.present? %> 
 <h3>エラーがあります。</h3>
 <ul <% @tweet.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
 <% end %> 
 </ul>
 <% end %> 


<%= form_for @tweet , url: {action: :create} do |f| %> 
<%= render partial: "form", :locals => {:f => f} %>
<% end %> 

app/views/tweets/show.html.erb
<p> 
<strong>タイトル：</strong>
<%= @tweet.message %> 
</p>
<p> 
<strong>時刻：</strong>
<%= @tweet.tdate %> 
</p>
<p>
</p>
<%= link_to 'Back',root_path%>